theme: jekyll-theme-cayman
title: Tensegrity Robotics
description: This webpage intends to list papers related to Tensegrity Robotics, links to tutorials and workshops, and pointers to existing implementations of Tensegrities.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  parse_block_html: true
include:
  - index.md
  - libraries.md
  - papers.md
  - tutorials.md
